# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: lib/gerdu.proto for package 'gerdu'

require 'grpc'
require './lib/gerdu_pb'

module Gerdu
  module Gerdu
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'gerdu.Gerdu'

      rpc :Put, ::Gerdu::PutRequest, ::Gerdu::PutResponse
      rpc :Get, ::Gerdu::GetRequest, ::Gerdu::GetResponse
      rpc :Delete, ::Gerdu::DeleteRequest, ::Gerdu::DeleteResponse
    end

    Stub = Service.rpc_stub_class
  end
end
