# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lib/gerdu.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("lib/gerdu.proto", :syntax => :proto3) do
    add_message "gerdu.PutResponse" do
      optional :created, :bool, 1
    end
    add_message "gerdu.PutRequest" do
      optional :key, :string, 1
      optional :value, :bytes, 2
    end
    add_message "gerdu.GetRequest" do
      optional :key, :string, 1
    end
    add_message "gerdu.GetResponse" do
      optional :value, :bytes, 1
    end
    add_message "gerdu.DeleteRequest" do
      optional :key, :string, 1
    end
    add_message "gerdu.DeleteResponse" do
      optional :deleted, :bool, 1
    end
  end
end

module Gerdu
  PutResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gerdu.PutResponse").msgclass
  PutRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gerdu.PutRequest").msgclass
  GetRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gerdu.GetRequest").msgclass
  GetResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gerdu.GetResponse").msgclass
  DeleteRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gerdu.DeleteRequest").msgclass
  DeleteResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gerdu.DeleteResponse").msgclass
end
